### ISSUE TITLE
I would suggest that DOSMID be able to support changing the OPL library

### ISSUE THREAD

**Issue by denjhang** [Tronix286/DOSMID#1]
DOSMID can use real OPL2/3 to play mid music, but it would be better if it can load the sound library in op2 or wopl format. At present, it seems that the sound of DOSMID using OPLx to play mid is immutable.

**Comment by Tronix286** [comment]
Iam not DOSMID author, this is a old fork from original DOSMID source code hosted at sourceforge ( https://dosmid.sourceforge.net/ ) by Mateusz Viste. This fork was created specifically for experimenting with a **C/MS Game Blaster** sound card based on two saa1099 psg. 
For OPL sound, you must firstly download the latest version of dosmid from the original site (here is an outdated version), and secondly, for support, write directly to the DOSMID author - Mateusz Viste.

**Comment by denjhang** [comment]
OK, I'll contact him directly.
